#
# Container for building Android Open Source Project (AOSP) master branch and
# AOSP master branch based projects, like LineageOS, CypherOS, AOKP, etc.
# More information at "http://source.android.com/source/initializing.html".
#
# All builds will be done by the "android" user. You should change this user's
# information when building the image to match the user running the container.
#

FROM ubuntu:16.04
MAINTAINER Otavio Cipriani <otavio.n.cipriani@gmail.com>

# Install required packages
RUN apt-get update && apt-get install -y --no-install-recommends bc bison \
  bsdmainutils build-essential ccache curl flex gcc-multilib git-core \
  g++-multilib gnupg gperf imagemagick less lib32ncurses5-dev lib32z-dev \
  libc6-dev-i386 libgl1-mesa-dev libx11-dev libxml2-utils lunzip \
  openjdk-8-jdk python-networkx rsync schedtool unzip x11proto-core-dev \
  xsltproc zip zlib1g-dev

# Add the "repo" tool
ADD https://storage.googleapis.com/git-repo-downloads/repo /usr/local/bin/repo
RUN chmod 0755 /usr/local/bin/repo

# Information about the "android" user
ARG ANDROID_GID=1000
ARG ANDROID_UID=1000
ARG ANDROID_NAME="Android Build User"
ARG ANDROID_EMAIL="android@localhost.localdomain"

# Create the "android" user and group
RUN groupadd --gid $ANDROID_GID android && useradd --gid android \
  --uid $ANDROID_UID --comment "Android Build User" --create-home android
USER android

# Configure git
RUN git config --global color.ui auto && \
  git config --global user.name "$ANDROID_NAME" && \
  git config --global user.email "$ANDROID_EMAIL"

# Set environment variables required to build Android
ENV USER=android \
    ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

# Mount point for the Android source tree
VOLUME /android

# This container should be run interactively
WORKDIR /android
ENTRYPOINT [ "/bin/bash" ]
